here=File.dirname(__FILE__)
$home=File.expand_path("#{here}/../..")
require "#{$home}/rakefile.rb"

run_id = (ENV['RUN_ID'] or  -1)

desc "Build everything."
task :all => [:buildGui, :build_python] 
make_python_targets(:build_python, FileList["python/**/*.py"])


desc "Clean everything."
task :clean => [:clean_python] 

training_home="#{$home}/data/directions/direction_training"



desc "cost function browser for forklift"
python_task :cost_function_browser => [:buildGui] do
    python("#{$pbd}/g3/inference/gui/costFunctionBrowser.py --use-rrt=False " +
           #"--model-filename=#{$home}/data/directions/direction_training/annotation/models/crf_discrete_pr2_1.5.pck " + 
           "--model-filename=#{$home}/data/directions/direction_training/annotation/models/crf_discrete_pr2_bolt_2012_1.5.pck " + 
           #"--model-filename=#{$home}/data/directions/direction_training/annotation/models/crf_continuous_pr2_bolt_2012_1.5.pck " + 
           "--limits=-10,10,-10,10 " +
           "--state-type=pr2 " +
           #"--start-state-file make_green_box_furthest_away_from_you.pck " + 
           #"--start-command 'Put the green block furthest away from you.' " +
           #"--start-command 'Put the green block in front of the orange block.'  " + 
           #"--start-state-file  orange_block_in_front_of_green_block.pck " + 
           #"--start-command 'drop it' " + 
           #"--start-state-file  holding_red_block.pck " + 
           #"--start-state-file red_block_close_to_blue.pck " + 
           "--start-context-file data/contexts/red_block_close_to_blue.yaml " + 
           "--start-command 'Pick up the red block' " +
           
           
           "--search-depth 2 " +
           "--beam-width 10 " +
           "--beam-width-event 10 " +
           ""
           )
end

python_task :partial_tests  do
  python("/usr/bin/nosetests  -v -s #{$pbd}/pr2/test/pr2_test.py")
end

desc "parse a bag file into a corpus"
python_task :parse_bag do
  #python("#{$pbd}/pr2/parse_bag.py")
  #python("#{$home}/tools/ros_bag_parser/src/bag_parser.py data/videos/08_pick_place_behind/08_pick_place_behind.bag")
  python("#{$home}/tools/ros_bag_parser/src/bag_parser.py data/videos/video1/test.bag")
  python("#{$home}/tools/ros_bag_parser/src/bag_parser.py data/videos/video2/test.bag")
  python("#{$home}/tools/ros_bag_parser/src/bag_parser.py data/videos/video3/test.bag")
  python("#{$home}/tools/ros_bag_parser/src/bag_parser.py data/videos/video4/test.bag")
  python("#{$home}/tools/ros_bag_parser/src/bag_parser.py data/videos/video5/test.bag")
  python("#{$home}/tools/ros_bag_parser/src/bag_parser.py data/videos/video6/test.bag")

  #python("#{$home}/tools/ros_bag_parser/src/bag_parser.py #{here}/test.bag")
end


desc "object annotator"
python_task :pr2_commander => [:buildGui] do
  python("#{$pbd}/pr2/gui/pr2CommanderGui.py " +
         "--model-filename=#{$home}/data/directions/direction_training/annotation/models/crf_discrete_pr2_bolt_2012_1.5.pck " + 
         #"--model-filename=#{$home}/data/directions/direction_training/annotation/models/crf_discrete_pr2_1.5.pck " + 
         #"--model-filename=#{$home}/data/directions/direction_training/annotation/models/crf_discrete_forklift_1.5.pck " + 
         ""
         )
end

desc "loads a list of annotation files and excutes the associated commands"
python_task :slu_evaluator do
  python("#{$pbd}/pr2/slu_evaluator.py " + 
         #"--corpus-filename #{here}/data/sls_bolt_summer_2012/slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.testing.yaml " + 
         #"--corpus-filename #{here}/data/sls_bolt_summer_2012/place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.testing.yaml " + 
         #"--corpus-filename #{here}/data/slu_evaluator_simple.yaml " + 
         "--corpus-filename #{here}/data/slu_evaluator_demo.yaml " + 
         ""
         )
end

desc "loads a list of annotation files and excutes the associated commands"
python_task :slu_evaluator_gui do
  python("#{$pbd}/pr2/gui/sluEvaluatorGui.py " + 
         #"--corpus-filename #{here}/data/sls_bolt_summer_2012/slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.testing.yaml " + 
         #"--corpus-filename #{here}/data/sls_bolt_summer_2012/place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.testing.yaml " + 
         #"--corpus-filename #{here}/data/slu_evaluator_simple.yaml " + 
         "--corpus-filename #{here}/data/slu_evaluator_demo.yaml " + 
         ""
         )
end


desc "starts up the push to talk gui for interacting with head_manager without speech localization output"
python_task :push_to_talk => [:buildGui] do
  python("#{$pbd}/pr2/gui/pushToTalk.py")
end

desc "rosbridge"
python_task :publisher do
  python("python/publisher.py")
  
end


desc "record"
python_task :record do
  #fname = "/home/andyh/pr2_training_videos_summer/IomxyrtX9ws.bag"
  #fname = "/home/andyh/pr2_training_videos_summer/BbZo019wffk.bag"
  #fname = "/home/andyh/pr2_training_videos_summer/fFbWvao-NL8.bag"
  #fname = "/home/andyh/pr2_training_videos_summer/_ENSl0x4Uz0.bag"
  sh("rosbag record /tf /mit/object_list /usb_cam/image_raw /rosout -O #{fname}")
  python("#{$home}/tools/ros_bag_parser/src/bag_parser.py #{fname}")
  #sh("bash -c 'source ~/.bin/rossim.sh && rosrun ros_bag_parser bag2video.sh #{fname}'")

end

desc "object annotator"
python_task :object_annotator do
 python("#{$pbd}/g3/annotation/gui/objectAnnotator.py " +
         "--state-type=pr2 " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.training.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/place_blue_block_on_opposite_side_of_red_block_t1u5yBymQtw.groundings.training.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/slide_blocks_into_a_square_3jEbxhbYEDg.groundings.training.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/slide_blue_block_behind_green_block_aB9loZ52Ox8.groundings.training.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/slide_orange_block_in_front_of_green_block_6MIjYMxOod8.groundings.training.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.training.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/pick_up_and_drop_red_block__ENSl0x4Uz0.groundings.training.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/stack_blue_on_red_and_orange_on_blue_BbZo019wffk.groundings.training.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/stack_red_block_on_blue_block_IomxyrtX9ws.groundings.training.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/make_2_by_2_vertical_square_fFbWvao-NL8.groundings.training.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.testing.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/place_blue_block_on_opposite_side_of_red_block_t1u5yBymQtw.groundings.testing.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/slide_blocks_into_a_square_3jEbxhbYEDg.groundings.testing.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/slide_blue_block_behind_green_block_aB9loZ52Ox8.groundings.testing.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/slide_orange_block_in_front_of_green_block_6MIjYMxOod8.groundings.testing.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.testing.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/pick_up_and_drop_red_block__ENSl0x4Uz0.groundings.testing.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/stack_blue_on_red_and_orange_on_blue_BbZo019wffk.groundings.testing.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/stack_red_block_on_blue_block_IomxyrtX9ws.groundings.testing.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/make_2_by_2_vertical_square_fFbWvao-NL8.groundings.testing.yaml " + 
         "--corpus-filename=#{here}/data/hackathon_2012_02_6_videos.yaml " + 
         "--corpus-filename=#{here}/data/hackathon_2012_02_6_videos_negative.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/easy_negative_objects_training.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/easy_negative_objects_testing.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/negative.training.yaml " + 
         "--corpus-filename=#{here}/data/sls_bolt_summer_2012/negative.testing.yaml "
        )
end


desc "Generate CRF plans on navigation dataset"
python_task :evaluate => [:buildGui] do
  python("#{$pbd}/g3/evaluator/evaluateParallel.py " +
         "--corpus-fname #{here}/data/sls_bolt_summer_2012/make_2_by_2_vertical_square_fFbWvao-NL8.groundings.testing.yaml " + 
         "--corpus-fname #{here}/data/sls_bolt_summer_2012/pick_up_and_drop_red_block__ENSl0x4Uz0.groundings.testing.yaml " + 
         "--corpus-fname #{here}/data/sls_bolt_summer_2012/place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.testing.yaml " + 
         "--corpus-fname #{here}/data/sls_bolt_summer_2012/place_blue_block_on_opposite_side_of_red_block_t1u5yBymQtw.groundings.testing.yaml " + 
         "--corpus-fname #{here}/data/sls_bolt_summer_2012/slide_blocks_into_a_square_3jEbxhbYEDg.groundings.testing.yaml " + 
         "--corpus-fname #{here}/data/sls_bolt_summer_2012/slide_blue_block_behind_green_block_aB9loZ52Ox8.groundings.testing.yaml " + 
         "--corpus-fname #{here}/data/sls_bolt_summer_2012/slide_orange_block_in_front_of_green_block_6MIjYMxOod8.groundings.testing.yaml " +
         "--corpus-fname #{here}/data/sls_bolt_summer_2012/slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.testing.yaml " + 
         "--corpus-fname #{here}/data/sls_bolt_summer_2012/stack_blue_on_red_and_orange_on_blue_BbZo019wffk.groundings.testing.yaml " + 
         "--corpus-fname #{here}/data/sls_bolt_summer_2012/stack_red_block_on_blue_block_IomxyrtX9ws.groundings.testing.yaml "  + 
         "--esdc-extractor annotated " + 
         "--model #{training_home}/annotation/models/crf_discrete_pr2_bolt_2012_1.5.pck " + 
         "--runid #{run_id} "+
         "--esdcmulti False " + 
         "--state-type=pr2 " +
         "--merging False " +
         "--entropy-metric metric2 " +
         "--num-questions 0 " +
         "--num-answers 0 " +
         "--resolver-type None " +
         "--force_sync False " +
         "--question_type targeted " + 
         "--cost-function-class CostFnCrf " + 
         "")
end


python_task :node_evaluation do
  python("#{$pbd}/g3/evaluator/evaluate_nodes.py " +
         "--result-fname #{here}/dataEvaluation/data/evaluation-run-#{run_id}/ " +
         "--state-type forklift " + 
         "--question_type None " + 
         "")
end


desc "View Evaluation Results"
python_task :evaluation_results_browser => [:buildGui] do
  sh "cd dataEvaluation && rake buildGui"
  use_rrt=false
  python("#{$pbd}/g3/evaluator/gui/evaluationResultsBrowser.py " + 
	 "#{training_home}/annotation/datasets/test_continuous_pr2_bolt_2012.pck " + 
         "#{here}/dataEvaluation/data/evaluation-run-#{run_id}/ " +
         "#{use_rrt} " +
         "--model-filename=#{$home}/data/directions/direction_training/annotation/models/crf_discrete_pr2_bolt_2012_1.5.pck " +
         "")
end

python_task :renumber_annotation_ids do
  python("#{$pbd}/esdcs/esdcIo/renumber_annotation_ids.py "  +
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/place_blue_block_on_opposite_side_of_red_block_t1u5yBymQtw.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/slide_blocks_into_a_square_3jEbxhbYEDg.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/slide_blue_block_behind_green_block_aB9loZ52Ox8.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/slide_orange_block_in_front_of_green_block_6MIjYMxOod8.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/pick_up_and_drop_red_block__ENSl0x4Uz0.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/stack_blue_on_red_and_orange_on_blue_BbZo019wffk.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/stack_red_block_on_blue_block_IomxyrtX9ws.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/make_2_by_2_vertical_square_fFbWvao-NL8.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/place_blue_block_on_opposite_side_of_red_block_t1u5yBymQtw.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/slide_blocks_into_a_square_3jEbxhbYEDg.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/slide_blue_block_behind_green_block_aB9loZ52Ox8.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/slide_orange_block_in_front_of_green_block_6MIjYMxOod8.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/pick_up_and_drop_red_block__ENSl0x4Uz0.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/stack_blue_on_red_and_orange_on_blue_BbZo019wffk.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/stack_red_block_on_blue_block_IomxyrtX9ws.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/make_2_by_2_vertical_square_fFbWvao-NL8.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/hackathon_2012_02_6_videos.yaml " + 
         "--corpus-fname=#{here}/data/hackathon_2012_02_6_videos_negative.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/easy_negative_objects_training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/easy_negative_objects_testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/negative.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/negative.testing.yaml ")
end


python_task :export_examples_from_inference do
  python("#{$pbd}/pr2/export_examples_from_inference.py "  +
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/place_blue_block_on_opposite_side_of_red_block_t1u5yBymQtw.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/slide_blocks_into_a_square_3jEbxhbYEDg.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/slide_blue_block_behind_green_block_aB9loZ52Ox8.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/slide_orange_block_in_front_of_green_block_6MIjYMxOod8.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/pick_up_and_drop_red_block__ENSl0x4Uz0.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/stack_blue_on_red_and_orange_on_blue_BbZo019wffk.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/stack_red_block_on_blue_block_IomxyrtX9ws.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/make_2_by_2_vertical_square_fFbWvao-NL8.groundings.training.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/place_blue_block_on_opposite_side_of_red_block_t1u5yBymQtw.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/slide_blocks_into_a_square_3jEbxhbYEDg.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/slide_blue_block_behind_green_block_aB9loZ52Ox8.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/slide_orange_block_in_front_of_green_block_6MIjYMxOod8.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/pick_up_and_drop_red_block__ENSl0x4Uz0.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/stack_blue_on_red_and_orange_on_blue_BbZo019wffk.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/stack_red_block_on_blue_block_IomxyrtX9ws.groundings.testing.yaml " + 
         "--corpus-fname=#{here}/data/sls_bolt_summer_2012/make_2_by_2_vertical_square_fFbWvao-NL8.groundings.testing.yaml " + 
         "--model-filename=#{$home}/data/directions/direction_training/annotation/models/crf_discrete_pr2_bolt_2012_1.5.pck " + 
         "")

end

desc "object annotator"
python_task :object_annotator_inference_export do
 python("#{$pbd}/g3/annotation/gui/objectAnnotator.py " +
        "--state-type=pr2 " + 

        "--corpus-filename data/sls_bolt_summer_2012/inference_examples_place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.training.yaml  " +
        #"--corpus-filename data/sls_bolt_summer_2012/inference_examples_place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/inference_examples_pick_up_and_drop_red_block__ENSl0x4Uz0.groundings.training.yaml  " +
        #"--corpus-filename data/sls_bolt_summer_2012/inference_examples_pick_up_and_drop_red_block__ENSl0x4Uz0.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/inference_examples_slide_orange_block_in_front_of_green_block_6MIjYMxOod8.groundings.training.yaml  " +
        #"--corpus-filename data/sls_bolt_summer_2012/inference_examples_slide_orange_block_in_front_of_green_block_6MIjYMxOod8.groundings.testing.yaml  " +


        "--corpus-filename data/sls_bolt_summer_2012/inference_examples_slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.training.yaml  " +
        #"--corpus-filename data/sls_bolt_summer_2012/inference_examples_slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/inference_examples_stack_red_block_on_blue_block_IomxyrtX9ws.groundings.training.yaml  " +
        #"--corpus-filename data/sls_bolt_summer_2012/inference_examples_stack_red_block_on_blue_block_IomxyrtX9ws.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/inference_examples_place_blue_block_on_opposite_side_of_red_block_t1u5yBymQtw.groundings.training.yaml  " +
        # "--corpus-filename data/sls_bolt_summer_2012/inference_examples_place_blue_block_on_opposite_side_of_red_block_t1u5yBymQtw.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/inference_examples_stack_blue_on_red_and_orange_on_blue_BbZo019wffk.groundings.training.yaml  " +
        # "--corpus-filename data/sls_bolt_summer_2012/inference_examples_stack_blue_on_red_and_orange_on_blue_BbZo019wffk.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/inference_examples_make_2_by_2_vertical_square_fFbWvao-NL8.groundings.training.yaml  " +
        # "--corpus-filename data/sls_bolt_summer_2012/inference_examples_make_2_by_2_vertical_square_fFbWvao-NL8.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/inference_examples_slide_blocks_into_a_square_3jEbxhbYEDg.groundings.training.yaml  " +
        # "--corpus-filename data/sls_bolt_summer_2012/inference_examples_slide_blocks_into_a_square_3jEbxhbYEDg.groundings.testing.yaml  " +
        
        "--corpus-filename data/sls_bolt_summer_2012/inference_examples_slide_blue_block_behind_green_block_aB9loZ52Ox8.groundings.training.yaml  " +
        # "--corpus-filename data/sls_bolt_summer_2012/inference_examples_slide_blue_block_behind_green_block_aB9loZ52Ox8.groundings.testing.yaml  " +

        "")
end


desc "object annotator"
python_task :object_annotator_place_export do
 python("#{$pbd}/g3/annotation/gui/objectAnnotator.py " +
        "--state-type=pr2 " + 
        "--corpus-filename data/sls_bolt_summer_2012/place_examples_place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.training.yaml  " +
        #"--corpus-filename data/sls_bolt_summer_2012/place_examples_place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/place_examples_pick_up_and_drop_red_block__ENSl0x4Uz0.groundings.training.yaml  " +
        #"--corpus-filename data/sls_bolt_summer_2012/place_examples_pick_up_and_drop_red_block__ENSl0x4Uz0.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/place_examples_slide_orange_block_in_front_of_green_block_6MIjYMxOod8.groundings.training.yaml  " +
        #"--corpus-filename data/sls_bolt_summer_2012/place_examples_slide_orange_block_in_front_of_green_block_6MIjYMxOod8.groundings.testing.yaml  " +


        "--corpus-filename data/sls_bolt_summer_2012/place_examples_slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.training.yaml  " +
        #"--corpus-filename data/sls_bolt_summer_2012/place_examples_slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/place_examples_stack_red_block_on_blue_block_IomxyrtX9ws.groundings.training.yaml  " +
        #"--corpus-filename data/sls_bolt_summer_2012/place_examples_stack_red_block_on_blue_block_IomxyrtX9ws.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/place_examples_place_blue_block_on_opposite_side_of_red_block_t1u5yBymQtw.groundings.training.yaml  " +
        # "--corpus-filename data/sls_bolt_summer_2012/place_examples_place_blue_block_on_opposite_side_of_red_block_t1u5yBymQtw.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/place_examples_stack_blue_on_red_and_orange_on_blue_BbZo019wffk.groundings.training.yaml  " +
        # "--corpus-filename data/sls_bolt_summer_2012/place_examples_stack_blue_on_red_and_orange_on_blue_BbZo019wffk.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/place_examples_make_2_by_2_vertical_square_fFbWvao-NL8.groundings.training.yaml  " +
        # "--corpus-filename data/sls_bolt_summer_2012/place_examples_make_2_by_2_vertical_square_fFbWvao-NL8.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/place_examples_slide_blocks_into_a_square_3jEbxhbYEDg.groundings.training.yaml  " +
        # "--corpus-filename data/sls_bolt_summer_2012/place_examples_slide_blocks_into_a_square_3jEbxhbYEDg.groundings.testing.yaml  " +
        
        "--corpus-filename data/sls_bolt_summer_2012/place_examples_slide_blue_block_behind_green_block_aB9loZ52Ox8.groundings.training.yaml  " +
        # "--corpus-filename data/sls_bolt_summer_2012/place_examples_slide_blue_block_behind_green_block_aB9loZ52Ox8.groundings.testing.yaml  " +

        "")
end



desc "object annotator"
python_task :object_annotator_free_place_export do
 python("#{$pbd}/g3/annotation/gui/objectAnnotator.py " +
        "--state-type=pr2 " + 
        "--corpus-filename data/sls_bolt_summer_2012/free_place_examples_place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.training.yaml  " +
        #"--corpus-filename data/sls_bolt_summer_2012/free_place_examples_place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/free_place_examples_pick_up_and_drop_red_block__ENSl0x4Uz0.groundings.training.yaml  " +
        #"--corpus-filename data/sls_bolt_summer_2012/free_place_examples_pick_up_and_drop_red_block__ENSl0x4Uz0.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/free_place_examples_slide_orange_block_in_front_of_green_block_6MIjYMxOod8.groundings.training.yaml  " +
        #"--corpus-filename data/sls_bolt_summer_2012/free_place_examples_slide_orange_block_in_front_of_green_block_6MIjYMxOod8.groundings.testing.yaml  " +


        "--corpus-filename data/sls_bolt_summer_2012/free_place_examples_slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.training.yaml  " +
        #"--corpus-filename data/sls_bolt_summer_2012/free_place_examples_slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/free_place_examples_stack_red_block_on_blue_block_IomxyrtX9ws.groundings.training.yaml  " +
        #"--corpus-filename data/sls_bolt_summer_2012/free_place_examples_stack_red_block_on_blue_block_IomxyrtX9ws.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/free_place_examples_place_blue_block_on_opposite_side_of_red_block_t1u5yBymQtw.groundings.training.yaml  " +
        # "--corpus-filename data/sls_bolt_summer_2012/free_place_examples_place_blue_block_on_opposite_side_of_red_block_t1u5yBymQtw.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/free_place_examples_stack_blue_on_red_and_orange_on_blue_BbZo019wffk.groundings.training.yaml  " +
        # "--corpus-filename data/sls_bolt_summer_2012/free_place_examples_stack_blue_on_red_and_orange_on_blue_BbZo019wffk.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/free_place_examples_make_2_by_2_vertical_square_fFbWvao-NL8.groundings.training.yaml  " +
        # "--corpus-filename data/sls_bolt_summer_2012/free_place_examples_make_2_by_2_vertical_square_fFbWvao-NL8.groundings.testing.yaml  " +

        "--corpus-filename data/sls_bolt_summer_2012/free_place_examples_slide_blocks_into_a_square_3jEbxhbYEDg.groundings.training.yaml  " +
        # "--corpus-filename data/sls_bolt_summer_2012/free_place_examples_slide_blocks_into_a_square_3jEbxhbYEDg.groundings.testing.yaml  " +
        
        "--corpus-filename data/sls_bolt_summer_2012/free_place_examples_slide_blue_block_behind_green_block_aB9loZ52Ox8.groundings.training.yaml  " +
        # "--corpus-filename data/sls_bolt_summer_2012/free_place_examples_slide_blue_block_behind_green_block_aB9loZ52Ox8.groundings.testing.yaml  " +

        "")
end


desc "object annotator"
python_task :print_corpus do
    python("#{$pbd}/pr2/print_corpus.py " +
           #"--corpus-filename data/sls_bolt_summer_2012/place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.training.yaml  " +
           "--corpus-filename data/sls_bolt_summer_2012/place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.testing.yaml  " +
           
           #"--corpus-filename data/sls_bolt_summer_2012/pick_up_and_drop_red_block__ENSl0x4Uz0.groundings.training.yaml  " +
           "--corpus-filename data/sls_bolt_summer_2012/pick_up_and_drop_red_block__ENSl0x4Uz0.groundings.testing.yaml  " +
           
           #"--corpus-filename data/sls_bolt_summer_2012/slide_orange_block_in_front_of_green_block_6MIjYMxOod8.groundings.training.yaml  " +
           "--corpus-filename data/sls_bolt_summer_2012/slide_orange_block_in_front_of_green_block_6MIjYMxOod8.groundings.testing.yaml  " +
           
           
           #"--corpus-filename data/sls_bolt_summer_2012/slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.training.yaml  " +
           "--corpus-filename data/sls_bolt_summer_2012/slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.testing.yaml  " +

           #"--corpus-filename data/sls_bolt_summer_2012/stack_red_block_on_blue_block_IomxyrtX9ws.groundings.training.yaml  " +
           "--corpus-filename data/sls_bolt_summer_2012/stack_red_block_on_blue_block_IomxyrtX9ws.groundings.testing.yaml  " +
           
           #"--corpus-filename data/sls_bolt_summer_2012/place_blue_block_on_opposite_side_of_red_block_t1u5yBymQtw.groundings.training.yaml  " +
            "--corpus-filename data/sls_bolt_summer_2012/place_blue_block_on_opposite_side_of_red_block_t1u5yBymQtw.groundings.testing.yaml  " +
           
           #"--corpus-filename data/sls_bolt_summer_2012/stack_blue_on_red_and_orange_on_blue_BbZo019wffk.groundings.training.yaml  " +
            "--corpus-filename data/sls_bolt_summer_2012/stack_blue_on_red_and_orange_on_blue_BbZo019wffk.groundings.testing.yaml  " +
           
           #"--corpus-filename data/sls_bolt_summer_2012/make_2_by_2_vertical_square_fFbWvao-NL8.groundings.training.yaml  " +
            "--corpus-filename data/sls_bolt_summer_2012/make_2_by_2_vertical_square_fFbWvao-NL8.groundings.testing.yaml  " +

           #"--corpus-filename data/sls_bolt_summer_2012/slide_blocks_into_a_square_3jEbxhbYEDg.groundings.training.yaml  " +
            "--corpus-filename data/sls_bolt_summer_2012/slide_blocks_into_a_square_3jEbxhbYEDg.groundings.testing.yaml  " +
           
           #"--corpus-filename data/sls_bolt_summer_2012/slide_blue_block_behind_green_block_aB9loZ52Ox8.groundings.training.yaml  " +
            "--corpus-filename data/sls_bolt_summer_2012/slide_blue_block_behind_green_block_aB9loZ52Ox8.groundings.testing.yaml  " +
           ""
           )  
end



desc "object annotator"
python_task :histograms do
    python("#{$pbd}/forklift/corpusAnalysis/esdcHistograms.py " +
           #"--corpus-filename data/sls_bolt_summer_2012/place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.training.yaml  " +
           "--corpus-filename data/sls_bolt_summer_2012/place_blue_block_between_red_and_orange_blocks_lv35RBc0RPE.groundings.testing.yaml  " +
           
           #"--corpus-filename data/sls_bolt_summer_2012/pick_up_and_drop_red_block__ENSl0x4Uz0.groundings.training.yaml  " +
           "--corpus-filename data/sls_bolt_summer_2012/pick_up_and_drop_red_block__ENSl0x4Uz0.groundings.testing.yaml  " +
           
           #"--corpus-filename data/sls_bolt_summer_2012/slide_orange_block_in_front_of_green_block_6MIjYMxOod8.groundings.training.yaml  " +
           "--corpus-filename data/sls_bolt_summer_2012/slide_orange_block_in_front_of_green_block_6MIjYMxOod8.groundings.testing.yaml  " +
           
           
           #"--corpus-filename data/sls_bolt_summer_2012/slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.training.yaml  " +
           "--corpus-filename data/sls_bolt_summer_2012/slide_red_block_closer_to_blue_block_KFotsdwOGlM.groundings.testing.yaml  " +

           #"--corpus-filename data/sls_bolt_summer_2012/stack_red_block_on_blue_block_IomxyrtX9ws.groundings.training.yaml  " +
           "--corpus-filename data/sls_bolt_summer_2012/stack_red_block_on_blue_block_IomxyrtX9ws.groundings.testing.yaml  " +
           
           #"--corpus-filename data/sls_bolt_summer_2012/place_blue_block_on_opposite_side_of_red_block_t1u5yBymQtw.groundings.training.yaml  " +
            "--corpus-filename data/sls_bolt_summer_2012/place_blue_block_on_opposite_side_of_red_block_t1u5yBymQtw.groundings.testing.yaml  " +
           
           #"--corpus-filename data/sls_bolt_summer_2012/stack_blue_on_red_and_orange_on_blue_BbZo019wffk.groundings.training.yaml  " +
            "--corpus-filename data/sls_bolt_summer_2012/stack_blue_on_red_and_orange_on_blue_BbZo019wffk.groundings.testing.yaml  " +
           
           #"--corpus-filename data/sls_bolt_summer_2012/make_2_by_2_vertical_square_fFbWvao-NL8.groundings.training.yaml  " +
            "--corpus-filename data/sls_bolt_summer_2012/make_2_by_2_vertical_square_fFbWvao-NL8.groundings.testing.yaml  " +

           #"--corpus-filename data/sls_bolt_summer_2012/slide_blocks_into_a_square_3jEbxhbYEDg.groundings.training.yaml  " +
            "--corpus-filename data/sls_bolt_summer_2012/slide_blocks_into_a_square_3jEbxhbYEDg.groundings.testing.yaml  " +
           
           #"--corpus-filename data/sls_bolt_summer_2012/slide_blue_block_behind_green_block_aB9loZ52Ox8.groundings.training.yaml  " +
            "--corpus-filename data/sls_bolt_summer_2012/slide_blue_block_behind_green_block_aB9loZ52Ox8.groundings.testing.yaml  " +
           ""
           )  
end



desc "object annotator"
python_task :object_annotator_hackathon do
 python("#{$pbd}/g3/annotation/gui/objectAnnotator.py " +
        "--state-type=pr2 " + 
        "--corpus-filename data/hackathon_2012_02_6_videos.yaml  ")
end

python_task :state_to_context do
  python("#{$pbd}/pr2/state_to_context.py")
end
