"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct
class object_enum_t(object):
    __slots__ = [ "value" ]
    UNKNOWN = 0
    SEMI_TRUCK = 1
    SEMI_TRUCK_WHEEL = 2
    FLATBED_TRUCK = 3
    FLATBED_TRUCK_WHEEL = 4
    FLATBED_TRAILER = 5
    FLATBED_TRAILER_WHEEL = 6
    LR3 = 7
    OPERATOR = 8
    BOX = 9
    DRUM_55GAL = 10
    SHIP_CONTAINER = 11
    SIGN_POST = 12
    BERM = 13
    FORKLIFT_BODY = 1000
    FORKLIFT_WHEEL = 1001
    FORKLIFT_MAST = 1002
    FORKLIFT_CARRIAGE = 1003
    FORKLIFT_TINE = 1004
    _packed_fingerprint = struct.pack(">Q", 0x55e7fb2c5bb7942)

    def __init__ (self, value):
        self.value = value

    def _get_hash_recursive(parents):
        return 0x55e7fb2c5bb7942
    _get_hash_recursive=staticmethod(_get_hash_recursive)
    def _get_packed_fingerprint():
        return object_enum_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def encode(self):
        return struct.pack(">Qi", 0x55e7fb2c5bb7942, self.value)
    def _encode_one(self, buf):
        buf.write (struct.pack(">i", self.value))

    def decode(data):
        if hasattr (data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != object_enum_t._packed_fingerprint:
            raise ValueError("Decode error")
        return object_enum_t(struct.unpack(">i", buf.read(4))[0])
    decode = staticmethod(decode)
    def _decode_one(buf):
        return object_enum_t(struct.unpack(">i", buf.read(4))[0])
    _decode_one = staticmethod(_decode_one)

