"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

import rect_list_t

import track_list_t

class obstacle_list_t(object):
    __slots__ = ["rects", "tracks"]

    def __init__(self):
        self.rects = None
        self.tracks = None

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(obstacle_list_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        self.rects._encode_one(buf)
        self.tracks._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != obstacle_list_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return obstacle_list_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = obstacle_list_t()
        self.rects = rect_list_t.rect_list_t._decode_one(buf)
        self.tracks = track_list_t.track_list_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if obstacle_list_t in parents: return 0
        newparents = parents + [obstacle_list_t]
        tmphash = (0x980a8d3d59cbba6+ rect_list_t.rect_list_t._get_hash_recursive(newparents)+ track_list_t.track_list_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff 
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None
    
    def _get_packed_fingerprint():
        if obstacle_list_t._packed_fingerprint is None:
            obstacle_list_t._packed_fingerprint = struct.pack(">Q", obstacle_list_t._get_hash_recursive([]))
        return obstacle_list_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

