"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

import pallet_slot_t

class pallet_slot_pair_t(object):
    __slots__ = ["utime", "left_slot", "right_slot", "confidence"]

    def __init__(self):
        self.utime = 0
        self.left_slot = None
        self.right_slot = None
        self.confidence = 0.0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(pallet_slot_pair_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        self.left_slot._encode_one(buf)
        self.right_slot._encode_one(buf)
        buf.write(struct.pack(">d", self.confidence))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != pallet_slot_pair_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pallet_slot_pair_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pallet_slot_pair_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.left_slot = pallet_slot_t.pallet_slot_t._decode_one(buf)
        self.right_slot = pallet_slot_t.pallet_slot_t._decode_one(buf)
        self.confidence = struct.unpack(">d", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pallet_slot_pair_t in parents: return 0
        newparents = parents + [pallet_slot_pair_t]
        tmphash = (0xd8e22778d1df589e+ pallet_slot_t.pallet_slot_t._get_hash_recursive(newparents)+ pallet_slot_t.pallet_slot_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff 
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None
    
    def _get_packed_fingerprint():
        if pallet_slot_pair_t._packed_fingerprint is None:
            pallet_slot_pair_t._packed_fingerprint = struct.pack(">Q", pallet_slot_pair_t._get_hash_recursive([]))
        return pallet_slot_pair_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

