"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

import pallet_manipulation_command_t

class pallet_manipulation_command_list_t(object):
    __slots__ = ["utime", "num_commands", "commands"]

    def __init__(self):
        self.utime = 0
        self.num_commands = 0
        self.commands = []

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(pallet_manipulation_command_list_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.num_commands))
        for i0 in range(self.num_commands):
            self.commands[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != pallet_manipulation_command_list_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pallet_manipulation_command_list_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pallet_manipulation_command_list_t()
        self.utime, self.num_commands = struct.unpack(">qi", buf.read(12))
        self.commands = []
        for i0 in range(self.num_commands):
            self.commands.append(pallet_manipulation_command_t.pallet_manipulation_command_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pallet_manipulation_command_list_t in parents: return 0
        newparents = parents + [pallet_manipulation_command_list_t]
        tmphash = (0xfcae6a71f29b4be6+ pallet_manipulation_command_t.pallet_manipulation_command_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff 
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None
    
    def _get_packed_fingerprint():
        if pallet_manipulation_command_list_t._packed_fingerprint is None:
            pallet_manipulation_command_list_t._packed_fingerprint = struct.pack(">Q", pallet_manipulation_command_list_t._get_hash_recursive([]))
        return pallet_manipulation_command_list_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

