"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

import point2d_t

class pointlist2d_t(object):
    __slots__ = ["npoints", "points"]

    def __init__(self):
        self.npoints = 0
        self.points = []

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(pointlist2d_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.npoints))
        for i0 in range(self.npoints):
            self.points[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != pointlist2d_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pointlist2d_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pointlist2d_t()
        self.npoints = struct.unpack(">i", buf.read(4))[0]
        self.points = []
        for i0 in range(self.npoints):
            self.points.append(point2d_t.point2d_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pointlist2d_t in parents: return 0
        newparents = parents + [pointlist2d_t]
        tmphash = (0x176526a9c69f4224+ point2d_t.point2d_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff 
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None
    
    def _get_packed_fingerprint():
        if pointlist2d_t._packed_fingerprint is None:
            pointlist2d_t._packed_fingerprint = struct.pack(">Q", pointlist2d_t._get_hash_recursive([]))
        return pointlist2d_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

