"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

import point3d_t

class pointlist3d_t(object):
    __slots__ = ["utime", "npoints", "points"]

    def __init__(self):
        self.utime = 0
        self.npoints = 0
        self.points = []

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(pointlist3d_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.npoints))
        for i0 in range(self.npoints):
            self.points[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != pointlist3d_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pointlist3d_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pointlist3d_t()
        self.utime, self.npoints = struct.unpack(">qi", buf.read(12))
        self.points = []
        for i0 in range(self.npoints):
            self.points.append(point3d_t.point3d_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pointlist3d_t in parents: return 0
        newparents = parents + [pointlist3d_t]
        tmphash = (0xee53b18544f90828+ point3d_t.point3d_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff 
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None
    
    def _get_packed_fingerprint():
        if pointlist3d_t._packed_fingerprint is None:
            pointlist3d_t._packed_fingerprint = struct.pack(">Q", pointlist3d_t._get_hash_recursive([]))
        return pointlist3d_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

