"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class rect_t(object):
    __slots__ = ["dxy", "size", "theta"]

    def __init__(self):
        self.dxy = [ 0.0 for dim0 in range(2) ]
        self.size = [ 0.0 for dim0 in range(2) ]
        self.theta = 0.0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(rect_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>2f', *self.dxy[:2]))
        buf.write(struct.pack('>2f', *self.size[:2]))
        buf.write(struct.pack(">f", self.theta))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != rect_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return rect_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = rect_t()
        self.dxy = struct.unpack('>2f', buf.read(8))
        self.size = struct.unpack('>2f', buf.read(8))
        self.theta = struct.unpack(">f", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if rect_t in parents: return 0
        tmphash = (0x407ed273a37c9f84) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff 
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None
    
    def _get_packed_fingerprint():
        if rect_t._packed_fingerprint is None:
            rect_t._packed_fingerprint = struct.pack(">Q", rect_t._get_hash_recursive([]))
        return rect_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

