"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class task_destination_checkpoint_t(object):
    __slots__ = ["utime", "clear", "checkpoint", "task_id"]

    def __init__(self):
        self.utime = 0
        self.clear = False
        self.checkpoint = 0
        self.task_id = 0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(task_destination_checkpoint_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbiq", self.utime, self.clear, self.checkpoint, self.task_id))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != task_destination_checkpoint_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return task_destination_checkpoint_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = task_destination_checkpoint_t()
        self.utime, self.clear, self.checkpoint, self.task_id = struct.unpack(">qbiq", buf.read(21))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if task_destination_checkpoint_t in parents: return 0
        tmphash = (0x2d14615d054f6e07) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff 
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None
    
    def _get_packed_fingerprint():
        if task_destination_checkpoint_t._packed_fingerprint is None:
            task_destination_checkpoint_t._packed_fingerprint = struct.pack(">Q", task_destination_checkpoint_t._get_hash_recursive([]))
        return task_destination_checkpoint_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

