"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct
class task_planner_state_enum_t(object):
    __slots__ = [ "value" ]
    TP_NAVIGATION = 0
    TP_APPROACH = 1
    TP_MANIPULATION = 2
    TP_IDLE = 3
    _packed_fingerprint = struct.pack(">Q", 0x38039c027f3ecfe8)

    def __init__ (self, value):
        self.value = value

    def _get_hash_recursive(parents):
        return 0x38039c027f3ecfe8
    _get_hash_recursive=staticmethod(_get_hash_recursive)
    def _get_packed_fingerprint():
        return task_planner_state_enum_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def encode(self):
        return struct.pack(">Qi", 0x38039c027f3ecfe8, self.value)
    def _encode_one(self, buf):
        buf.write (struct.pack(">i", self.value))

    def decode(data):
        if hasattr (data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != task_planner_state_enum_t._packed_fingerprint:
            raise ValueError("Decode error")
        return task_planner_state_enum_t(struct.unpack(">i", buf.read(4))[0])
    decode = staticmethod(decode)
    def _decode_one(buf):
        return task_planner_state_enum_t(struct.unpack(">i", buf.read(4))[0])
    _decode_one = staticmethod(_decode_one)

