"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

import track_t

class track_list_t(object):
    __slots__ = ["utime", "ntracks", "tracks"]

    def __init__(self):
        self.utime = 0
        self.ntracks = 0
        self.tracks = []

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(track_list_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.ntracks))
        for i0 in range(self.ntracks):
            self.tracks[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != track_list_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return track_list_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = track_list_t()
        self.utime, self.ntracks = struct.unpack(">qi", buf.read(12))
        self.tracks = []
        for i0 in range(self.ntracks):
            self.tracks.append(track_t.track_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if track_list_t in parents: return 0
        newparents = parents + [track_list_t]
        tmphash = (0xc6357f083f36ff28+ track_t.track_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff 
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None
    
    def _get_packed_fingerprint():
        if track_list_t._packed_fingerprint is None:
            track_list_t._packed_fingerprint = struct.pack(">Q", track_list_t._get_hash_recursive([]))
        return track_list_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

