here=File.dirname(__FILE__)
$home=File.expand_path("#{here}/../..")
require "#{$home}/rakefile.rb"

run_id = (ENV['RUN_ID'] or  -1)

desc "Build everything."
task :all => [:buildGui, :build_python] 
make_python_targets(:build_python, FileList["python/**/*.py"])


desc "Clean everything."
task :clean => [:clean_python] 

