here=File.dirname(__FILE__)
$home=File.expand_path("#{here}/../..")
require "#{$home}/rakefile.rb"

desc "Build everything."
task :all => [:build_python, :build_java] 

make_jar_target("slu-mallet.jar")

task :setup do
  sh "cd 3rdParty/mallet && rake setup"
end

desc "Clean everything."
task :clean => [:clean_python] 


desc "Run the test cases."
python_task :partial_tests  do
  python("/usr/bin/nosetests -v " + 
         "#{$pbd}/mallet/test/jvm_test.py ")
  python("/usr/bin/nosetests -collect-only -v -s " + 
         "#{$pbd}/mallet/learners/test/CRFMallet_test.py")
end


