here=File.dirname(__FILE__)
$slu_home=File.expand_path("#{here}/../..")
require "#{$slu_home}/rakefile.rb"

desc "Build everything."
task :all => [:build_python] 
make_python_targets(:build_python, FileList["python/**/*.py"])

desc "Clean everything."
task :clean => [:clean_python] 

training_home="#{$slu_home}/data/directions/direction_training"



python_task :run_tests do
  python("#{$pbd}/unit_tests/slu.py")
end
