here=File.dirname(__FILE__)
$home=File.expand_path("#{here}/../..")
require "#{$home}/rakefile.rb"

desc "Build everything."
task :all => [:build_python] 

desc "Clean everything."
task :clean => [:clean_python] 

training_home="#{$home}/data/directions/direction_training"



python_task :run_tests do
  python("#{$pbd}/unit_tests/slu.py")
end
