here=File.dirname(__FILE__)
$slu_home=File.expand_path("#{here}/../..")
require "#{$slu_home}/rakefile.rb"

desc "Build everything."

task :all do
end
task :setup do
  sh "cd 3rdParty/slu_features && rake setup"
end
