here=File.dirname(__FILE__)
$slu_home=File.expand_path("#{here}/../..")
require "#{$slu_home}/rakefile.rb"

make_python_targets(:build_python, FileList["python/*.py"])

desc "Build everything."
task :all => [:build_python] 



desc "Clean everything."
task :clean => [:clean_python] 


desc "Run the test cases."
python_task :partial_tests do
  #python("/usr/bin/nosetests -v #{$pbd}/tokenizer_test.py")
  #python("/usr/bin/nosetests -v #{$pbd}/stopwords_test.py")
  python("/usr/bin/nosetests quaternion_test")
end
