here=File.dirname(__FILE__)
$home=File.expand_path("#{here}/../..")
require "#{$home}/rakefile.rb"
task :all => [:build_python] 
make_python_targets(:build_python, FileList["python/**/*.py"])
task :clean => [:clean_python] 

task :setup do
  mkdir_p("#{$data_home}/stanford-parser")
  sh "cd 3rdParty/stanford-parser/ && rake setup"
end

desc "Run the test cases."
task :partial_tests  do
  #python("/usr/bin/nosetests python/stanford_parser/dependencies_test.py")
  python("/usr/bin/nosetests python/stanford_parser/parser_test.py")
end


desc "Run the test cases."
task :tests do
  python("/usr/bin/nosetests -v python")
end

task :sandbox => :build_python do
	python("#{$pbd}/stanford_parser/parser_sandbox.py")
end


