here=File.dirname(__FILE__)
$home=File.expand_path("#{here}/../..")
require "#{$home}/rakefile.rb"

desc "Build everything."
task :all => [:buildGui, :build_python] 


desc "Clean everything."
task :clean => [:clean_python] 

desc "Run the test cases."
python_task :partial_tests  do
  python("/usr/bin/nosetests -v -s #{$pbd}/forklift/test/forklift_test.py")  
end

desc "cost function browser for forklift"
python_task :spatial_relations_gui => [:buildGui] do
    python("#{$pbd}/spatial_relations/gui/spatial_relations_gui.py " +
           "--model-filename=#{$home}/tools/crf_training/models/crf_discrete_sr_1.5.pck " + 
           ""
           )
end


desc "cost function browser for forklift"
python_task :path_heatmaps do
    python("#{$pbd}/spatial_relations/gui/path_heatmaps.py " +
           "--model-filename=#{$home}/tools/crf_training/models/crf_discrete_sr_1.5.pck " + 
           ""
           )
end
